[General]
DisplayServer=wayland

[Wayland]
# As of this was written, sddm defaults to run on X11 and occuping dgpu. Force it to use wayland as a workaround. Maybe not needed in the future.
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1