# If you use looking-glass with ivshmem, the file's default permission is qemu:qemu 0660,
# so your looking-glass client won't be able to access it.
# While the first line is typically enough, the second line ensures that if any other program
# has generated it with different permissions (and SELinux context), systemd will fix it.
# NOTE: The default selinux label shipped in Fedora 44 is not right for this file.
# Run `sudo semanage fcontext -a -t svirt_tmpfs_t '/dev/shm/looking-glass'` first.

f /dev/shm/looking-glass 0660 username kvm -
z /dev/shm/looking-glass
